micronaut:
  server:
    max-request-size: '100MB'
    multipart:
      maxFileSize: 100MB

  application:
    name: concurrentBathInsert
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: TESTDB
    password: harak4892
    driverClassName: oracle.jdbc.driver.OracleDriver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages:
        - 'com.harak.domain'
      classpath: false
    compile-time-hibernate-proxies: true
